### ISSUE TITLE
embed PDFs break copy/paste

### ISSUE THREAD

**Issue by vap0rtranz** [redhat-partner-tech/partner-tech-days#1]
Viewing the embedded PDFs docs breaks copy/paste of the commands.

**Comment by vap0rtranz** [comment]
To expand on the 2 problems:

1. hidden chars are in the PDF doc, even if downloaded
2. Github's embedded viewer of PDFs doesn't copy the text

This appears in the OCP JEE8 Part 1 lab.

**Comment by redhat-partner-tech** [comment]
Download PDF and open in native viewer. We should add note to respective README.md's. Closing since event is past.
