### ISSUE TITLE
JEE8 Part1: switch to builder image & avoid local mvn

### ISSUE THREAD

**Issue by vap0rtranz** [redhat-partner-tech/partner-tech-days#2]
RE: JEE8 Part1 Lab

Switch to using a builder image so we can avoid having to locally install & setup Maven.  Obviously this prevents Part2 Lab but we can't expect that users have a working mvn.

Instead of building artifact locally `mvn clean package` after `oc new-build --image-stream=jboss-eap72-openshift:1.0 --binary=true --name=weather-app`

Replace with sti/builder image as `oc new-app eap72-openshift~https://github.com/tqvarnst/weather-app.git`

Standard users cannot import images into the hosted registry, so cluster-admin must also do a `oc import-image .. --confirm`

**Comment by redhat-partner-tech** [comment]
Closing since event is past. Address in RHPTS-Q4
